sudo: required
services: 
  - docker

before_install:
  - docker build -t panagiotisganelis/docker-react -f Dockerfile.dev .  

script:
  - docker run panagiotisganelis/docker-react npm run test -- --coverage  